pure_pursuit:
  ros__parameters:
    waypoints_path: "/home/bhajneet/sim_racing/ros2_ws/src/pure_pursuit/racelines/first_map.csv"
    odom_topic: "/odom"
    car_refFrame: "f1tenth_1"
    global_refFrame: "world"
    drive_topic: "/drive"
    rviz_current_waypoint_topic: "/current_waypoint"
    rviz_lookahead_waypoint_topic: "/lookahead_waypoint"

    # Pure Pursuit Parameters
    # Lookahead is computed using the following: lookahead = min(max(min_lookahead, max_lookahead * curr_velocity / lookahead_ratio), max_lookahead);
    min_lookahead: 0.1 # for square track
    # min_lookahead: 1.0 # for larger track
    max_lookahead: 1.0 # lookahead when the car is going around max velocity
    lookahead_ratio: 1.0 # approximately the max velocity
    # K_p: 0.25 # for square track
    K_p: 0.05 # for big track
    # K_p: 5.0
    
    steering_limit: 1.0
    velocity_percentage: 0.01 # the limit, can only do 1 lap with clean tires

waypoint_visualizer_node:
  ros__parameters:
    waypoints_path: "/home/bhajneet/sim_racing/ros2_ws/src/pure_pursuit/racelines/first_map.csv"
